name: Compilar e implantar o aplicativo .NET Core

on:
  push:
    branches:
      - main

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore ${{ secrets.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ secrets.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ${{ secrets.PROJECT_PATH }} --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ secrets.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ secrets.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Logout
        run: az logout
